node{
    deleteDir()
    checkout scm
    def shareMethod = load("jobs/ShareMethod.groovy")
    def label_name = "slave_build_node01"
    lock(label:label_name, quantity:1){
        resources_name = shareMethod.getLockedResourceName(label_name)
        if(resources_name.size() > 0){
            node_name = resources_name[0]
        }
        else
	    {
            error("Failed to find resource with label " + label_name)
        }
        node(node_name){
            deleteDir()
            dir("hackathon"){
                checkout scm
            }
            stage("build base image"){
                withCredentials([
                    usernamePassword(credentialsId: 'JENKINS_SUDO_USER',
                                     passwordVariable: 'SUDO_PASSWORD',
                                     usernameVariable: 'SUDO_USER'),
                    usernamePassword(credentialsId: 'HACKTHON_CI_DOCKER_HUB',
                         passwordVariable: 'DOCKERHUB_PASS',
                         usernameVariable: 'DOCKERHUB_USER')
                ]){
                    sh '''#!/bin/bash -x
                    ./hackathon/pipelines/build-base-docker-image/build_base_image.sh
                    '''
                    archiveArtifacts 'hackathon_pipeline_docker.tar'
                }
            }
        }
    }
}

