node{
        try{
            // Manifest will be stashed after this stage
            stage("Parse Pull Request"){
            }

            stage("Unit Test"){
            }

            stage("Function Test"){
            }
}
